name: Build
on: [push, pull_request]
jobs:
    release:
        name: Release
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release@16
